language: python
python:
- 3.4
install:
- pip install -e .
- pip install -r requires/testing.txt
script: flake8 bandoleers
sudo: false
deploy:
  provider: pypi
  user: aweber
  password:
    secure: gEx1yVcGtVCQWfZOjyaK38ipqCRi70HrzjFrPpFYM3qf6B+s356ahRN5IuviS2HlgIvGGoK40tK4EMbQrwQRT7Cq5a5NoW4HTo9h4bAkLdtw+3vRgAIGs795BkcTb7LT5B7y0w3vcZRXxnhqFmsWkPF+FYxBp62lCT0mrei9sG3oyi8oGvPvjTlxz5J9XOwMPqxX9UpNR1VDJTG0rRCQBkST2369RjA+lPeHE9x0AeUtqLLmwVMMNWv3oBIIQaTFMDKgphmySfHEsv01ndTFfKYOwaXQN2gnyLKBpoRnG3u9I8hE9BweutlwiWfvrG5C+lZsOS9d/8idh/Fcgsb2CEO7FDqRsvMMiNtiExWReXXQ3mcquMtxYaq9O/GvlyXaKXTHHy1CVkUlQMJWyc2qzxXboNTSHNR3fRrhOv2BHIrtVuxzgbiU9vF6YPRdmZ9NdAuZxaVYsJORnLscPHCxCtPpZuHQ6nzR2V3mA7E6NYFH2pIsuEPaxs+xVH3YG6d9DcftmBJzx1adyGNtkeFILf8QS16upGTLXiWkWo2c/SQv1TffdK+TKIpwDwhgwP7aDWn5+glryHJEpKxkp1Q8pmmS7BFzn6V8lT783HnRhzAHfJmZ9WsEXQkg+knhcGDJYDYA7bsWvkQbRMHh9B7NA7YCtUFRbBIMQxDQ+UO6ZmY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    all_branches: true
    python: 3.4
